#appearance
general { 
    gaps_in = 0
    gaps_out = 0

    border_size = 0

    col.active_border = rgb(00FFFF)
    col.inactive_border = rgb(1C1C1C)

    resize_on_border = false 

    allow_tearing = true
}

decoration {
    rounding = 0

    active_opacity = 1
    inactive_opacity = 1
	
    shadow {
        enabled = false
    }

    blur {
        enabled = false
    }
}

animations {
    enabled = false

    bezier = basic, 0.75, 0, 0.25, 1
    bezier = linear, 0, 0, 1, 1

    animation = windows, 1, 0.2, basic
    animation = windowsOut, 1, 0.2, basic
    animation = border, 1, 1, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 0.2, basic
}

misc { 
    force_default_wallpaper = 2
    disable_hyprland_logo = false
    enable_anr_dialog = false
}
