hl.on("hyprland.start", function()    
    hl.exec_cmd("uwsm app -- hyprpolkitagent")
    hl.exec_cmd("uwsm app -- mako")
    hl.exec_cmd("uwsm app -- hyprpaper")
    hl.exec_cmd("uwsm app -- waybar")
    hl.exec_cmd("hyprctl setcursor Bibata-Modern-Classic 32")
end)